# Site settings
title: webmakersteve
email: me@webmakersteve.com
description: "A blog of my ramblings as a programmer, gamer, and person. Those are in no particular order."
baseurl: ""
url: "http://www.webmakersteve.com"
twitter_username: webmakersteve
github_username:  webmakersteve

# Build settings
markdown: kramdown
permalink: pretty
