# Site settings
title: webmakersteve
email: me@webmakersteve.com
description: "A blog of my ramblings as a programmer, gamer, and person. Those are in no particular order."
baseurl: ""
url: "http://www.webmakersteve.com"
twitter_username: webmakersteve
github_username:  webmakersteve

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5
paginate_path: blog/page:num

# Sass
sass:
    sass_dir: _sass
    style: compressed

# Collections
collections:
  projects:
    foo: bar
    #permalink: /projects/:path/
